# -*- coding: utf-8 -*-
"""coding problem

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jMdYbEIPDWkewGXXQTv8EZFNYjr29AA7
"""

user_input=input()
convert_lower=user_input.lower()
count=0
for i in convert_lower:
  if i=="a" or i=="e" or i=="i" or i=="o" or i=="u":
    count+=1
print(count)

user_units=int(input())
if (user_units<=100):
  total_bill=user_units*3
  print(total_bill)
elif (user_units>100 and user_units<=150):
  total_bill=(100*3)+((user_units-100)*4)
  print(total_bill)
elif (user_units>150 and user_units<=200):
  total_bill=(100*3)+(50*4)+((user_units-150)*5)
  print(total_bill)
else:
  total_bill=(100*3)+(50*4)+(50*5)+((user_units-200)*10)
  print(total_bill)

x=int(input())
y=int(input())

total_sum = 0
for i in range(x+1,y+1):
    print(i)
    total_sum = total_sum + i

print(total_sum)

s=int(input())
sum=1
for number in range(s):
  m=int(input())
  sum*=m
print(sum)

name=input()
print(name)
"m" in name
"a" in name
"n" in name
"u" in name
reverse_name=name[::-1]
print(reverse_name)
if name==reverse_name:
  print("true")
else:
  print("false")

#without using slicling
name= input()
reverse_name =""
for pos in name:
  reverse_name=pos+reverse_name
print(reverse_name)
if name==reverse_name:
  print("polindrome")
else:
  print("not polindrome")

number=int(input())
reverse_numb=0
while(number>0):
  remanider=number%10
  reverse_numb=reverse_numb*10+remanider
  number=number//10
print(reverse_numb)

number=int(input())
for i in range(1,number):
  print(i)

number=int(input())
sum=0
for i in range(1,number):
  if number%i==0:
    sum+=i
if sum==number:
  print("perfect number")
else:
  8
  6
  print("not perfect")

n=int(input())
count=0
for i in range(1,n+1):
  if(n%i==0):
    count+=1
  else:
    pass
if(count>2):
   print("True")
else:
  print("False")

n = int(input())
m = int(input())
for i in range(n):
  if(i%2!=0):
     print("+ "*m)
  else:
    print("- "*m)

n = int(input())
m = int(input())
for i in range(n,m+1):
  if(i%2!=0):
     print("+ "*m)
  else:
    print("- "*m)

n = int(input())
m = int(input())
for i in range(1,n+2):
  if(i==1 or i==n+1):
    print("+"+"-"*((m+2)-2)+"+")
  else:
    print("|"+" "*((m+2)-2)+"|")

#prime numbers
n=int(input())
count=1
for i in range(2,n+1):
  if(n%i==0):
    count+=1
if(count==2):
   print("True")
else:
  print("False")

n = int(input())
for i in range(2,n+1):
  if n>1:
    fact = 0
  else:
    fact = 1
  for j in range(2,i):
      if i%j==0:
        fact+=1
  if fact == 0:
       print(i)
  else:
    pass

# finding max value
list1=[1,4,2,3,9]
max = 0
for i in list1:
    if i<max:
        max=max
    else:
        max=i
print(max)

# finding max value through user input
user = int(input())
max = 0
for i in range(user):
    n=int(input())
    if n<max:
        max=max
    else:
        max=n
print(max)

#finding max by appending the values in empty list
user = int(input())
list = []
max = 0
for i in range(user):
    n=int(input())
    list.append(n)
    if n<max:
        max=max
    else:
        max=n
print(max)

#finding max value using map and split function
list = list(map(int,input().split()))
print(list)
max = 0
for i in list:
    # list.append(n)
    if i<max:
        max=max
    else:
        max=i
print(max)

n=int(input())
m=int(input())
subscript=0
for i in range(m+n):
  print(i)

T=int(input())
for i in range(T):
  N,X=map(int,input().split)
  if N>6:
    remainder=N%6
    if remainder==0:
      print((N//6) *X)
    else:
      adding_one = int (N//6)+1
      print(adding_one*X)
  else:
    print(N*X)

x = int(input())
  if x<= 7:
    print("yes")
  else:
    print("no")

n=int(input("enter the number"))
for i in range(1,n+1):
    print("1")

    for j in range(1,11):
      print("1")

n=int(input())
for i in range(1,n+1):
    string_normal=""
    string_reverse=""
    spaces =n-1
    for j in range(1,i+1):
        string_reverse=str(j)+string_reverse
        string_normal+=str(j)
end_string=((spaces*" ")+string_reverse)
start_string=(string_normal+spaces*"")
print(start_string+(spaces*" ")+end_string)

n = int(input("Enter the number: "))
for i in range(n, 0, -1):
    string_name = ""
    for j in range(1, i + 1):
        string_name += str(j)
    print(string_name)

n=int(input("enter the number"))
for i in range(1,n-1):
    string_name=""
    spaces =n-1
    sum=0
    for j in range(1,i+1):
        string_name =str(j)+string_name
        sum+=j
    print(string_name+(spaces*" ")+str(sum))

list = list(map(int,input().split()))
max=0
s_max=0
for i in list:
    if i>max:
        s_max=max
        max=i
    elif(s_max<i and i!=max):
            s_max=i
print(s_max)

n=int(input())
m=int(input())
subscript=0
for i in range(m+n):
  print(i)

n=int(input("enter the number"))
for i in range(1,n+1):
    string_name=""
    spaces =n-1
    sum=0
    for j in range(1,i+1):
        string_name =str(j)+string_name
        sum+=j
    print(string_name+(spaces*" ")+str(sum))

n=int(input())
for i in range(1,11):
   for j in range(1,11):
     print(str(i)+"*"+str(j)+"="+str(i*j))
   print()

n=int(input(10,2))

for i in range(n):
  if ():
    print("minimun value")
  else:
    print("maximum value")

user_array = list(map(int, input().split()))
min_numb = user_array[0]
max_numb = user_array[0]

for num in user_array:
    if num < min_numb:
        min_numb = num
    if num > max_numb:
        max_numb = num

print("Minimum number:", min_numb)
print("Maximum number:", max_numb)

x=int(input())
list =[1,2,34,5,7,4,8,9,12]
list.sort()
print(list)
for i in list:
  if i==x:
    print("true")
    break
  else:
    print("false")
    break

x=int(input())
list = [5, 2, 9, 1]
if x in list:
  print("true")
else:
  print("false")

x=int(input())
list =[1,2,34,5,7,4,8,9,12]
list.sort()
print(list)
for i in list:
  if x==i:
    count=1
    break
  else:
    count=0
if count==1:
    print("true")
else:
    print("false")