# -*- coding: utf-8 -*-
"""day4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1efFDc9qUPtd_8MYY0zhSUmfmruKBJkbW
"""

user_units=int(input())
if (user_units<=100):
  total_bill=user_units*3
  print(total_bill)
elif (user_units>100 and user_units<=150):
  total_bill=(100*3)+((user_units-100)*4)
  print(total_bill)
elif (user_units>150 and user_units<=200):
  total_bill=(100*3)+(50*4)+((user_units-150)*5)
  print(total_bill)
else:
  total_bill=(100*3)+(50*4)+(50*5)+((user_units-200)*10)
  print(total_bill)#enter the user input

