# -*- coding: utf-8 -*-
"""matplotlib

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P1bCE6WuJxaLYXkaQiiji3zohckBqx5P
"""

pip install matplotlib

import matplotlib.pyplot as plt
import pandas as pd

x = [1,2,3]
y = [4,5,6]

plt.plot(x,y)
plt.grid()
plt.show()

import pandas as pd
data = {
    "salary": [25000,30000,37000,2800,39000,4800,55000]
}
df = pd.DataFrame(data)
print(df.head())
df.shape


plt.plot(df["salary"])
plt.grid()
plt.show()

plt.plot(df["salary"],color="green",marker = "o",linestyle = ":",linewidth = 8)
plt.grid()
plt.show()

plt.hist(df["salary"],bins=4,color="purple")

plt.show()

df["dept"] = ["HR","IT","FINANCE","HR","IT","FINANCE","HR"]
df.head()

count = df["dept"].value_counts()
count

plt.pie(count,labels=count.index,autopct="%2.8f%%",explode=[0,0,0])
plt.show()

df["age"] = [22,25,34,20,23,21,30]
df.head()

plt.bar(df["age"],df["salary"],color="blue",width=0.5)
plt.show()