# -*- coding: utf-8 -*-
"""numpy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gKh5R0m_j5OY0w0wbvHYmuP8kIWOjM4b
"""

pip install numpy

import numpy as np
arr1 = np.array([1,2,3,4,5,])
print(arr1)

print(arr1[2:])

import numpy as np
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

import numpy as np
arr2[1] [1]

import numpy as np
arr2[0] [2]

for i in range(len(arr2)):
  for j in range(len(arr2[i])):
    print(i,j)

for i in range(len(arr2)):
  for j in range(len(arr2[i])):
    print(i*j)

for i in range(len(arr2)):
  for j in range(len(arr2[i])):
    print(i**j)

for i in range(len(arr2)):
  for j in range(len(arr2[i])):
    print(i+j)

import numpy as np
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
x=arr3[0][1][2]
print(x)

print(arr2.shape)
print(arr2.size)
print(arr2.dtype)



print(arr3.shape)
print(arr3.size)
print(arr3.dtype)

print("Zero function")
print(np.zeros((3,3)))
print("_____________________")
print("Ones function")
print(np.ones((2,2)))
print("_____________________")
print("Identity matrix")
print(np.eye(3))
print("_____________________")
print("arrange function")
print(np.arange(0,10,2))
print("_____________________")
print("linespace function")
print(np.linspace(1,5,10))

print(np.arange(0,101,50))

print(np.linspace(1,5,10))

a = np.array([1,2,3])
b = np.array([4,5,6])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(np.dot(a,b))

a=np.random.rand(3,5)
print(a)

b=np.random.randint(1,50,(3,5))
print(b)



arr1=np.array([1,2,3])
arr1=np.array([4,5,6])
print("add:",arr1+arr2)
print("sub:",arr1-arr2)