# -*- coding: utf-8 -*-
"""pandas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eysc7PCm0wtOGWQPhzJRhHjN1HPVHueg
"""

pip install pandas

import pandas as pd
a = [1,True,"Rishi"]

myvar = pd.Series(a)
print(myvar)

print(myvar[1])

a = [1,True,"Manu"]

myvar = pd.Series(a, index = ["x","y","z"])
print(myvar)

print(myvar["y"])

import pandas as pd
data = {
    "Names": ["manu","Rishi","Tanu"],
    "age": [20,21,22],
    "score": [90,91,92]
}

df = pd.DataFrame(data)
print(df)

print(df.loc[0])

print(df.at[0,"Names"])

print()

import pandas as pd
series_example = [1,2,3,4,5]
df = pd.DataFrame(series_example,index=["x","y","z","a","d"])
print(df)
print(df.loc["x"])

import pandas as pd
df = pd.read_csv("people_data.csv")
print(df)
#df.head()

df = pd.read_csv("people_data.csv",usecols=["First Name","Sex","Email","Job Title"],nrows=5)

print(df)

df = pd.read_csv("people_data.csv",usecols=["First Name","Sex","Email","Job Title"],skiprows = [4,5])

print(df)

g=df.groupby("Job Title")
g.get_group("Games developer")

filtered_df = df.loc[df["Sex"]=="Male",["First Name","Job Title"]]
print(filtered_df)

filtered_df = df.query('Sex == "Male" and `Job Title` == "Games developer"')
print(filtered_df)