# -*- coding: utf-8 -*-
"""seaborn

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JOJBR23OpayLjlWJVgf5jG7rZgQ5c0ky
"""

import seaborn as sns
import matplotlib.pyplot as plt

df =  sns.load_dataset('iris')

sns.pairplot(df)
plt.show()



sns.pairplot(df, hue='species')
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

df = sns.load_dataset("iris")

corrr = df.corr(numeric_only=True)


sns.heatmap(corrr, annot=True,cmap="YlGnBu")
plt.title("Correlation Heatmap")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

df = sns.load_dataset("iris")

sns.countplot(data=df, x="species")
plt.title("Count Plot of Species")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

df = sns.load_dataset("iris")

sns.boxplot(data=df, x="species",y="petal_length")
plt.title("Count Plot of Species")
plt.show()